from typing import List, Dict, Any, Optional, Literal
from datetime import datetime

from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

# ============================================================================
# Input Schema
# ============================================================================

class NetworkPolicyGenerationInput(BaseModel):
    """
    Input for NetworkPolicy generation.
    """
    app_name: str = Field(..., description="Application name")
    
    allow_ingress_from_namespaces: List[str] = Field(default=[], description="Namespaces to allow ingress from")
    
    allow_egress_to_internet: bool = Field(False, description="Allow egress to internet")
    
    class Config:
        extra = "forbid"

# ============================================================================
# Output Schema
# ============================================================================

class NetworkPolicyGenerationOutput(BaseModel):
    yaml_content: str = Field(..., description="Content of network-policy.yaml")
    file_name: str = Field(default="network-policy.yaml")
    validation_status: Literal["valid", "warning", "error"] = Field(...)
    validation_messages: List[str] = Field(default=[])
    metadata: Dict[str, Any] = Field(default={})

# ============================================================================
# Tool Implementation
# ============================================================================

NETWORK_POLICY_GENERATOR_SYSTEM_PROMPT = """You are an expert Kubernetes NetworkPolicy generator.

## YOUR ROLE

Generate a NetworkPolicy manifest with Helm templating.

## TEMPLATE

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "CHARTNAME.fullname" . }}
  labels:
    {{- include "CHARTNAME.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "CHARTNAME.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.allowIngress }}
  - from:
    {{- range .Values.networkPolicy.allowIngress }}
    - namespaceSelector:
        matchLabels:
          name: {{ . }}
    {{- end }}
  {{- end }}
  egress:
  {{- if .Values.networkPolicy.allowEgress }}
  - to:
    {{- range .Values.networkPolicy.allowEgress }}
    - ipBlock:
        cidr: {{ .cidr }}
    {{- end }}
  {{- end }}
```

## REQUIREMENTS

1. Use `networking.k8s.io/v1` API
2. Target the Deployment generated by `generate_deployment_yaml` via selector
3. Use Helm values for rules

## OUTPUT FORMAT

Return ONLY the YAML content.
"""

def create_network_policy_user_prompt(input_data: NetworkPolicyGenerationInput) -> str:
    return f"""Generate NetworkPolicy YAML for:
**App Name:** {input_data.app_name}
**Allow Ingress From:** {input_data.allow_ingress_from_namespaces}
**Allow Egress Internet:** {input_data.allow_egress_to_internet}

Ensure proper Helm templating.
"""

def extract_yaml_from_response(response: str) -> str:
    import re
    yaml_pattern = r'```yaml\n(.*?)\n```'
    match = re.search(yaml_pattern, response, re.DOTALL)
    if match:
        return match.group(1)
    return response.strip()

def validate_yaml_syntax(yaml_content: str) -> tuple[str, List[str]]:
    from ruamel.yaml import YAML
    yaml = YAML()
    try:
        yaml.load(yaml_content)
        return "valid", []
    except Exception as e:
        return "error", [str(e)]

@tool("generate_network_policy_yaml", args_schema=NetworkPolicyGenerationInput, return_direct=False)
def generate_network_policy_yaml(input_data: NetworkPolicyGenerationInput) -> NetworkPolicyGenerationOutput:
    """
    Generates NetworkPolicy manifest.
    """
    
    llm = ChatOpenAI(
        model="gpt-4o",
        temperature=0.1,
        max_tokens=2048
    )
    
    response = llm.invoke([
        {"role": "system", "content": NETWORK_POLICY_GENERATOR_SYSTEM_PROMPT},
        {"role": "user", "content": create_network_policy_user_prompt(input_data)}
    ])
    
    yaml_content = extract_yaml_from_response(response.content)
    validation_status, validation_messages = validate_yaml_syntax(yaml_content)
    
    return NetworkPolicyGenerationOutput(
        yaml_content=yaml_content,
        validation_status=validation_status,
        validation_messages=validation_messages,
        metadata={
            "model": "gpt-4o",
            "timestamp": datetime.now().isoformat()
        }
    )
