"""Security module for K8s Autopilot — approval modes, command safety, unicode & SSRF defense."""

from k8s_autopilot.security.approval_mode import (
    APPROVAL_MODE_NAMESPACE,
    ApprovalMode,
    ApprovalModePayload,
    approval_mode_key,
    approval_mode_payload,
    aread_approval_mode_from_store,
    awrite_approval_mode,
    coerce_approval_mode,
    has_auto_mode_notice,
    has_yolo_acknowledgement,
    next_approval_mode,
    read_approval_mode_from_store,
    save_auto_mode_notice,
    save_yolo_acknowledgement,
    yolo_acknowledgement_path,
)
from k8s_autopilot.security.approval_mode_source import (
    ApprovalPolicyResolver,
    _approval_mode_source,
    _aresolve_approval_mode,
    _DecidedMode,
    _LiveLookup,
    _resolve_approval_mode,
)
from k8s_autopilot.security.shell_safety import (
    DANGEROUS_SHELL_PATTERNS,
    DEVOPS_DESTRUCTIVE_COMMANDS,
    DEVOPS_SAFE_COMMANDS,
    K8S_DANGEROUS_PATTERNS,
    K8S_SAFE_COMMANDS,
    classify_command,
    contains_dangerous_patterns,
    is_shell_command_allowed,
)
from k8s_autopilot.security.unicode_security import (
    UnicodeIssue,
    UrlSafetyResult,
    check_url_safety,
    detect_dangerous_unicode,
    format_warning_detail,
    iter_string_values,
    looks_like_url_key,
    render_with_unicode_markers,
    sanitize_control_chars,
    strip_dangerous_unicode,
    summarize_issues,
)
from k8s_autopilot.security.url_validation import (
    _is_blocked_ip,
    _pinned_dns,
    _UrlValidationError,
    _validate_url,
)

__all__ = [
    # Approval mode
    "APPROVAL_MODE_NAMESPACE",
    # Shell safety
    "DANGEROUS_SHELL_PATTERNS",
    "DEVOPS_DESTRUCTIVE_COMMANDS",
    "DEVOPS_SAFE_COMMANDS",
    "K8S_DANGEROUS_PATTERNS",
    "K8S_SAFE_COMMANDS",
    "ApprovalMode",
    "ApprovalModePayload",
    "ApprovalPolicyResolver",
    # Unicode safety
    "UnicodeIssue",
    "UrlSafetyResult",
    "_DecidedMode",
    "_LiveLookup",
    # URL validation & SSRF
    "_UrlValidationError",
    "_approval_mode_source",
    "_aresolve_approval_mode",
    "_is_blocked_ip",
    "_pinned_dns",
    "_resolve_approval_mode",
    "_validate_url",
    "approval_mode_key",
    "approval_mode_payload",
    "aread_approval_mode_from_store",
    "awrite_approval_mode",
    "check_url_safety",
    "classify_command",
    "coerce_approval_mode",
    "contains_dangerous_patterns",
    "detect_dangerous_unicode",
    "format_warning_detail",
    "has_auto_mode_notice",
    "has_yolo_acknowledgement",
    "is_shell_command_allowed",
    "iter_string_values",
    "looks_like_url_key",
    "next_approval_mode",
    "read_approval_mode_from_store",
    "render_with_unicode_markers",
    "sanitize_control_chars",
    "save_auto_mode_notice",
    "save_yolo_acknowledgement",
    "strip_dangerous_unicode",
    "summarize_issues",
    "yolo_acknowledgement_path",
]
