"""Plugin protocol, discovery, marketplace, and manifest module for K8s Autopilot."""

from k8s_autopilot.plugins.adapters.skills import (
    namespaced_skill_name,
    plugin_skill_roots,
    plugin_skill_sources,
)
from k8s_autopilot.plugins.discovery import (
    PluginDiscovery,
    add_marketplace_source_async,
    discover_plugins,
    discover_plugins_async,
    get_plugin_errors_async,
    install_plugin_async,
    list_available_plugins_async,
    remove_marketplace_async,
    set_plugin_enabled_async,
    uninstall_plugin_async,
)
from k8s_autopilot.plugins.manifest import (
    PluginManifestError,
    build_inventory,
    find_manifest_path,
    load_manifest,
)
from k8s_autopilot.plugins.marketplace import (
    MarketplaceError,
    find_marketplace_manifest,
    load_marketplace,
    load_marketplace_location,
    materialize_marketplace_source,
    materialize_plugin_source,
    parse_marketplace_source,
)
from k8s_autopilot.plugins.models import (
    ComponentInventory,
    InstalledPluginEntry,
    MarketplacePluginEntry,
    MarketplaceRecord,
    PluginDiscoveryResult,
    PluginInstance,
    PluginManifest,
    PluginMarketplace,
    PluginSource,
    split_plugin_id,
)
from k8s_autopilot.plugins.store import (
    add_installed_plugin_entry_async,
    cache_and_register_plugin,
    load_all_enabled_plugin_ids_async,
    load_installed_plugins_async,
    load_marketplace_records_async,
    remove_installed_plugin_entry_async,
    versioned_cache_path,
)

__all__ = [
    "ComponentInventory",
    "InstalledPluginEntry",
    "MarketplaceError",
    "MarketplacePluginEntry",
    "MarketplaceRecord",
    "PluginDiscovery",
    "PluginDiscoveryResult",
    "PluginInstance",
    "PluginManifest",
    "PluginManifestError",
    "PluginMarketplace",
    "PluginSource",
    "add_installed_plugin_entry_async",
    "add_marketplace_source_async",
    "build_inventory",
    "cache_and_register_plugin",
    "discover_plugins",
    "discover_plugins_async",
    "find_manifest_path",
    "find_marketplace_manifest",
    "get_plugin_errors_async",
    "install_plugin_async",
    "list_available_plugins_async",
    "load_all_enabled_plugin_ids_async",
    "load_installed_plugins_async",
    "load_manifest",
    "load_marketplace",
    "load_marketplace_location",
    "load_marketplace_records_async",
    "materialize_marketplace_source",
    "materialize_plugin_source",
    "namespaced_skill_name",
    "parse_marketplace_source",
    "plugin_skill_roots",
    "plugin_skill_sources",
    "remove_installed_plugin_entry_async",
    "remove_marketplace_async",
    "set_plugin_enabled_async",
    "split_plugin_id",
    "uninstall_plugin_async",
    "versioned_cache_path",
]
